[window]
title = "S2S Audio Stream"
width = 400  # 0 = auto-size to content
height = 0
min_width = 0
min_height = 0
always_on_top = false
resizable = true
position = "default"  # Options: default, center, top-left, top-right, bottom-left, bottom-right

[audio]
samplerate = 44100
blocksize = 256
dtype = "float32"
channels = 2
input = 24
output = 32
#resample_buffer_threshold = 4096
#resample_buffer_threshold = 1024
resample_buffer_threshold = 4410


#Device 22: Voicemeeter Out B1 (VB-Audio Voicemeeter VAIO)
#  Input Channels: 8
#  Output Channels: 0
#  Sample Rate: 44100.0 Hz

#Device 32: Voicemeeter VAIO3 Input (VB-Audio Voicemeeter VAIO)
#  Input Channels: 0
#  Output Channels: 8
#  Sample Rate: 44100.0 Hz

[monitoring]
enabled = false
device = 19
samplerate = 44100
#blocksize = 256
blocksize = 128 #256
dtype = "float32"
channels = 8

#Device 40: Voicemeeter AUX Input (VB-Audio Voicemeeter VAIO)
#  Input Channels: 0
#  Output Channels: 8
#  Sample Rate: 44100.0 Hz

[vad]
enabled = true
model = "silero"
samplerate = 16000
speech_prob_threshold = 0.30 #0.35
buffer_chunk_size = 512
silence_threshold_frames = 0
post_speech_silence_frames = 1 
pre_speech_frames = 2
max_buffer_frames = 16000

[stt]
model = "whisper"
model_path = ".models/stt/faster"
device = "cuda"
compute_type = "float16"
initial_prompt = "Speech-to-speech translation. Clear voice transcription."
language = "en"
beam_size = 1
word_timestamps = true
vad_filter = false
tokens = ".models/stt/sherpa/tokens.txt"
encoder = ".models/stt/sherpa/encoder-epoch-99-avg-1.onnx"
decoder = ".models/stt/sherpa/decoder-epoch-99-avg-1.onnx"
joiner = ".models/stt/sherpa/joiner-epoch-99-avg-1.onnx"

[tts]
default_voice = "en_US-hfc_female-medium"
use_cuda = true
samplerate = 44100

[voice_processing]
speed = 1.0
pitch = 0.0

[filters.lowpass]
enabled = true
cutoff = 6000
order = 2
btype = "low"
analog = false

[filters.highpass]
enabled = false
cutoff = 80
order = 2
btype = "high"
analog = false

[input_cleaning.highpass]
enabled = true
cutoff = 85
order = 4
btype = "high"
analog = false

[input_cleaning.lowpass]
enabled = true
cutoff = 7500
order = 4
btype = "low"
analog = false

[training]
capture = false