[training]
# Flask configuration
flask_host = "127.0.0.1"
flask_port = 8277
flask_debug = false

# Database configuration
database_path = "C:\\Users\\Aspen\\Dev\\database\\database.db"

# Model configuration
stt_model_path = ".\\.models\\stt\\whisper"
stt_faster_model_path = ".\\.models\\stt\\faster"

# Training arguments
batch_size = 32               # Increased from 4
gradient_accumulation_steps = 1 # 5090 is fast enough to do 1-step updates
learning_rate = 2e-5          # Slightly higher is okay for 'Small' variant
warmup_steps = 100            # Increased for stability
num_train_epochs = 3          
save_steps = 50               # Save more often since it's fast
eval_steps = 50               
logging_steps = 10            
bf16 = true                 # Ensure this is ON for speed/memory efficiency