[training]
# Flask configuration
flask_host = "127.0.0.1"
flask_port = 8277
flask_debug = false

# Database configuration
database_path = "C:\\Users\\Aspen\\Dev\\database\\database.db"

# Model configuration
stt_model_path = ".\\.models\\stt\\whisper"
stt_faster_model_path = ".\\.models\\stt\\faster"

# Training arguments
batch_size = 4
gradient_accumulation_steps = 2
learning_rate = 1e-5
warmup_steps = 50
num_train_epochs = 3
save_steps = 100
eval_steps = 100
logging_steps = 25
